// adjectives and nouns generated by Tabnine coding assistant
export const getRandomDisplayName = (id: string): string => {
    const adjectives = ['Adventurous', 'Brave', 'Clever', 'Curious', 'Determined', 'Eager', 'Enthusiastic', 'Fearless', 'Gentle', 'Happy', 'Kind', 'Loyal', 'Mysterious', 'Nervous', 'Obedient', 'Quiet', 'Respectful', 'Silent', 'Smart', 'Sociable', 'Strong', 'Thoughtful', 'Trustworthy', 'Warm', 'Wise'];
    const nouns = ['Bear', 'Cat', 'Dog', 'Elephant', 'Frog', 'Giraffe', 'Hippopotamus', 'Iguana', 'Jaguar', 'Kangaroo', 'Lion', 'Monkey', 'Narwhal', 'Octopus', 'Panda', 'Quail', 'Rabbit', 'Squirrel'];

    const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
    const noun = nouns[Math.floor(Math.random() * nouns.length)];
    return [adjective, noun, id.slice(0, 5)].join("_");
}